<a href="https://colab.research.google.com/github/MuhamadRizky101/Data/blob/main/WAML_Perceptron_201810370311180.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('data_nilai.csv')
data.head(7)

id_mhs  nilai1  nilai2       status
0   M001      71      92        Lulus
1   M002     100      82        Lulus
2   M003      78      82        Lulus
3   M004      89      79        Lulus
4   M005      42      21  Tidak Lulus
5   M006      52      30  Tidak Lulus
6   M007      47      32  Tidak Lulus

In [ ]:
data.describe()

nilai1     nilai2
count  100.00  100.00000
mean    65.87   64.27000
std     23.70   23.11231
min     20.00   20.00000
25%     46.00   45.75000
50%     69.50   69.00000
75%     89.25   82.00000
max    100.00  100.00000

In [ ]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['status'] = label_encoder.fit_transform(df['status'])
data['status'].unique()

array([0, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
X = np.array(data['nilai1']).reshape(-1,1)
scaler = StandardScaler()
x_scaler = scaler.fit_transform(X)
data['nilai1']=x_scaler

Y = np.array(data['nilai2']).reshape(-1,1)
scaler = StandardScaler()
y_scaler = scaler.fit_transform(Y)
data['nilai2']=y_scaler

In [ ]:
data.head()

id_mhs    nilai1    nilai2  status
0   M001  0.217546  1.205838       0
1   M002  1.447339  0.770988       0
2   M003  0.514393  0.770988       0
3   M004  0.980866  0.640533       0
4   M005 -1.012247 -1.881594       1

In [ ]:
data.drop(['id_mhs'], axis=1).head()

nilai1    nilai2  status
0  0.217546  1.205838       0
1  1.447339  0.770988       0
2  0.514393  0.770988       0
3  0.980866  0.640533       0
4 -1.012247 -1.881594       1

In [ ]:
data_x = data[['nilai1', 'nilai2']]
x = np.array(data_x)
x[0:5]

array([[ 0.21754616,  1.20583785],
       [ 1.44733927,  0.77098828],
       [ 0.51439277,  0.77098828],
       [ 0.98086602,  0.64053341],
       [-1.01224695, -1.88159408]])

In [ ]:
import numpy as np
data_y = data['status']
y = np.array(data_y)
y[0:5]

array([0, 0, 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)
print('Train Set:', x_train.shape, y_train.shape)
print('Test Set:', x_test.shape, y_test.shape)

Train Set: (90, 2) (90,)
Test Set: (10, 2) (10,)


In [ ]:
class Perceptron(object):
    
    def __init__(self, num_of_inputs, epochs=10, learning_rate=1):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.weights = np.zeros(num_of_inputs + 1)
    
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        if summation >= 0:
            activation = 1
        else:
            activation = 0
        print('output', activation)
        return activation
    
    def train(self, training_inputs, labels):
        i = 0
        for _ in range(self.epochs):
            i += 1
            print('###EPOCHS###', i)
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] = self.weights[1:] + self.learning_rate * (label - prediction) * inputs
                self.weights[0] = self.weights[0] + self.learning_rate * (label - prediction)
                print('label', label)
                print('weight', self.weights[1:])
                print('bias', self.weights[0])
                print(' ') 

In [ ]:
# Data
training_inputs = []
for dt_X_train in np.array(x_train):
  training_inputs.append (np.array(dt_X_train))

labels = np.array(y_train)

# Training
perceptron = Perceptron(2)
perceptron.train(training_inputs, labels)

###EPOCHS### 1
output 1
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 1
label 1
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias -1.0
 
output 0
label 0
weight [-1.108086   -0.64053341]
bias 

In [ ]:
# Prediksi menggunakan data train

data_compare_train = []
for data in np.array(x_train):
  data_compare_train.append(perceptron.predict(data))

n = 0
data_labels = list (y_train)
for x in range (len(data_compare_train)):
  if data_compare_train[x] == data_labels[x] :
    n+=1

accuracy = (n/len(data_compare_train))*100
print ('\nAccuracy :', accuracy)

output 0
output 0
output 1
output 1
output 1
output 1
output 0
output 0
output 1
output 0
output 0
output 0
output 1
output 1
output 0
output 0
output 1
output 1
output 0
output 1
output 1
output 0
output 0
output 1
output 1
output 1
output 0
output 0
output 0
output 0
output 0
output 1
output 0
output 1
output 1
output 0
output 1
output 1
output 1
output 1
output 1
output 0
output 0
output 0
output 0
output 1
output 1
output 0
output 0
output 1
output 0
output 1
output 0
output 1
output 0
output 0
output 0
output 0
output 1
output 1
output 1
output 1
output 0
output 0
output 1
output 0
output 0
output 0
output 1
output 1
output 0
output 1
output 0
output 1
output 0
output 1
output 1
output 0
output 0
output 0
output 1
output 1
output 0
output 1
output 1
output 1
output 1
output 1
output 1
output 1

Accuracy : 100.0


In [ ]:
#uji perceptron pada data test

data_compare_test = []
for data in np.array(x_test):
  data_compare_test.append(perceptron.predict(data))

n = 0
data_labels = list (y_test)
for x in range (len(data_compare_test)):
  if data_compare_test[x] == data_labels[x] :
    n+=1

accuracy = (n/len(data_compare_test))*100
print ('\nAccuracy :', accuracy)

output 1
output 0
output 1
output 0
output 0
output 0
output 0
output 1
output 0
output 0

Accuracy : 100.0
